import 'package:emart_app/consts/consts.dart';

const appname = "Beyond Nilkhet";
const appversion = "Version 1.0.0";
const credits = "@Team Alone";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "John Doe";
const forgetpass = 'Forget Password';
const login = "Login";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "Log in With";
const privacyPolicy = "Privacy Policy";
const termsandcond = "Terms and Conditions";
const alreadyHaveAccount = "Already Have an Account?";
